import type { Metadata } from "next";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import {NextIntlClientProvider} from 'next-intl';
import { Inter } from 'next/font/google'
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
    title: "Flow",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const locale = cookieStore.get("locale")?.value;
    return (
        <html
            lang={locale}
            className={inter.className}
        >
            <body>
                <NextIntlClientProvider locale={locale}>
                    <NuqsAdapter>{children}</NuqsAdapter>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
